// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => const FirebaseOptions(
    apiKey: 'AIzaSyDXcWptJ0B7Zn7YfiBeZnmqzgszWTxm5VY',
    appId: '1:67492072688:web:f9f6c12cf898f0c6490635',
    messagingSenderId: '67492072688',
    projectId: 'homzen-shoping',
    authDomain: 'homzen-shoping.firebaseapp.com',
    storageBucket: 'homzen-shoping.firebasestorage.app',
    measurementId: 'G-78G7XCJXLN',
  );

  static FirebaseOptions get android => const FirebaseOptions(
    apiKey: 'AIzaSyAnH4MI4LvzEuSY9kHqq9eDPxmxKS2CU20',
    appId: '1:67492072688:android:158b39c1dc9a2d20490635',
    messagingSenderId: '67492072688',
    projectId: 'homzen-shoping',
    storageBucket: 'homzen-shoping.firebasestorage.app',
  );

  static FirebaseOptions get ios => const FirebaseOptions(
    apiKey: 'AIzaSyA4dIXvRrbzDnETPWsMIBE4XKbQny7ZVfs',
    appId: '1:67492072688:ios:0ec8e6f6589e6fc9490635',
    messagingSenderId: '67492072688',
    projectId: 'homzen-shoping',
    storageBucket: 'homzen-shoping.firebasestorage.app',
    iosBundleId: 'com.homzen.shoping.service.siam',
  );

  static FirebaseOptions get macos => const FirebaseOptions(
    apiKey: 'AIzaSyA4dIXvRrbzDnETPWsMIBE4XKbQny7ZVfs',
    appId: '1:67492072688:ios:0ec8e6f6589e6fc9490635',
    messagingSenderId: '67492072688',
    projectId: 'homzen-shoping',
    storageBucket: 'homzen-shoping.firebasestorage.app',
    iosBundleId: 'com.homzen.shoping.service.siam',
  );

  static FirebaseOptions get windows => const FirebaseOptions(
    apiKey: 'AIzaSyDXcWptJ0B7Zn7YfiBeZnmqzgszWTxm5VY',
    appId: '1:67492072688:web:ad9e34c87c294887490635',
    messagingSenderId: '67492072688',
    projectId: 'homzen-shoping',
    authDomain: 'homzen-shoping.firebaseapp.com',
    storageBucket: 'homzen-shoping.firebasestorage.app',
    measurementId: 'G-KED4NRQCPS',
  );
}